version: "3"
services:
  app:
    build: .
    environment:
      - PORT
      - VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY
      - WKHTMLTOPDF_COMMAND=/bin/wkhtmltopdf
      - WKHTMLTOPDF_SHELL=/bin/sh
    ports:
      - $PORT:$PORT
    # volumes:
    #   - /app/node_modules
